[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ac in ac out power supply"
authors = [{name = "Jari Honkanen", email = "hardwaredescriptions@gmail.com"}]
dynamic = ["version", "description"]
